#!/bin/bash

# the first command line argument 
file_name=$1

# -z checks if first input is empty or null
if [ -z "$1" ]; then
    echo "No file name!"
    exit # stops exetuction 
else 
    touch "$file_name"
fi
# executing bash command from bash script


# text variable, no empty spaces between equal sign.
text="###\n\ndef main():\n\tpass\n\nif __name__ == '__main__':\n\tmain()"

# echo with -e allows to use escape characters like /n, /t etc.
echo -e $text >> $file_name

echo "File was created, mate. Code away!"

# 
code "$file_name"
